; Defines flocktrax-sync worksheet targets
;
;*********************
; ** NO SECRET KEYS **
;*********************
;
SEDBERRY_FARM_SHEETID=16m8gWs_MSClI_AuvkiH5IkK2xQE3gG26YId9cKh_FjY
WOAPE_SHEETID=1t550d5pGJOg3VT6rCb5siEZ2p3e-wOTKdQI4k7eYyNA