"use client";
import { useRef, useState } from 'react';
import { DeviceMobile, Desktop, Database, PlugsConnected } from '@phosphor-icons/react';

const components = [
 {name:'FlockTrax-Mobile', role:'Collect where the work happens', stack:'React Native / Expo · iOS & Android', Icon:DeviceMobile, description:'FlockTrax-Mobile is intentionally lean, focusing primarily on data collection while displaying an Active Barns/Flocks summary on a live dashboard. Workers use phones and tablets to enter flock activity, feed deliveries and work orders. Multiple authorized team members contribute to the same operational records. Special functions such as scheduling and flock closeouts are handled only through the FlockTrax-Admin console, keeping the Mobile app as simple and lean as possible.', points:['Farm and barn context keeps field entry tied to the correct flock.','Authenticated API calls apply the shared business rules and save records to the central database.','A successful save makes the record available to Admin—there is no separate end-of-day submission.']},
 {name:'FlockTrax-Admin', role:'Manage across the operation', stack:'Next.js / React · browser application', Icon:Desktop, description:'Farm managers and integrators work from a browser to review field records, manage placements, plan feed, follow work orders and close out flocks.', points:['Farm groups, farms, barns and placements give the operation a consistent structure.','Dashboards and reports read the shared records rather than a separately submitted field dataset.','Administrative tools maintain configuration, schedules and user access.','Because FlockTrax-Admin reads from the shared server-based database, multiple authenticated managers with the appropriate permissions and memberships can work simultaneously from anywhere with internet access.','Admin can also run side by side in separate browser windows on the same desktop. One window can display a list of closeout flocks while another opens a feed ticket for adjustment, keeping the workflow moving without navigating away from the original list.']},
 {name:'Shared data platform', role:'One authoritative flock record', stack:'Supabase · PostgreSQL · Auth · Storage', Icon:Database, description:'The cloud data platform connects both applications. PostgreSQL holds structured operational records; document storage retains supporting originals associated with those records.', points:['Authentication, role and farm-scope controls govern access to operational data.','Server-side functions and database operations provide common validation and business logic.','Original documents support review of the sources behind flock inputs throughout the flock lifecycle.','The cloud database server also provides connection traffic management, continuous monitoring of overall data security and performance, transaction processing and near-real-time backup capabilities.']},
 {name:'Integration services', role:'Connect the surrounding business', stack:'APIs · scheduled workers · queued synchronization', Icon:PlugsConnected, description:'Integration services exchange selected information with external systems without requiring workers to re-enter the same field records.', points:['The current BinSentry API connection brings external feed-monitoring readings into feed planning.','Google Cloud / Sheets workflows synchronize selected flock data with existing corporate information workflows.','Weather services provide farm-location context. Other feed-monitoring and corporate-system connections can be adapted to suitable APIs and agreed data mappings.']}
];
export function TechnicalArchitecture(){
 const [selected,setSelected]=useState(2);
 const detailDialog=useRef<HTMLDialogElement>(null);
 const item=components[selected];
 const card=(index: number)=>{const c=components[index];return <button className={`architecture-node node-${index}`} aria-pressed={selected===index} aria-haspopup="dialog" onClick={()=>{setSelected(index);detailDialog.current?.showModal();}}><c.Icon size={32} weight="duotone"/><span className="architecture-number">0{index+1}</span><strong>{c.name}</strong><span>{c.role}</span></button>};
 return <div className="architecture">
 <p className="eyebrow">Platform architecture</p><h3>Four components. One connected operation.</h3>
 <p className="architecture-intro">From a grower’s barns to an integrator’s network, the structure stays the same: two purpose-built applications, a shared data platform and services that connect the wider business.</p>
 <figure className="architecture-art"><div className="architecture-interactive-image"><img className="architecture-brand-bird" src="/marketing/media/flocktrax-bird-original.svg" alt=""/><img src="/marketing/media/architecture-big-picture-modules.png" width="1536" height="1024" alt="FlockTrax architecture: Admin browser console and Mobile workers across Farms A, B and C connect through authenticated services to one shared cloud data platform. Integration services connect feed monitoring, corporate information systems and weather. New add-on modules: Flock Processing Stats, Nutrient Management Plan Support, Organic System Plan Support and ROC Plan Support."/>{[0,1,2,3].map(index=><button key={index} className={`architecture-hotspot hotspot-${index}`} aria-label={`Explore ${components[index].name} in the diagram`} aria-haspopup="dialog" onClick={()=>{setSelected(index);detailDialog.current?.showModal();}}><span>Explore {components[index].name}</span></button>)}</div><figcaption>Conceptual system illustration · select a component below for implementation details. <a href="/marketing/media/architecture-big-picture-modules.png" target="_blank" rel="noreferrer">View full size</a></figcaption></figure>
 <div className="architecture-controls" role="group" aria-label="Explore the four platform components">{[0,1,2,3].map(index=><div key={index}>{card(index)}</div>)}</div>
 <dialog ref={detailDialog} className="architecture-detail architecture-dialog" aria-labelledby="architecture-dialog-title" onClick={event=>{if(event.target===detailDialog.current)detailDialog.current?.close();}}><button className="architecture-close" autoFocus onClick={()=>detailDialog.current?.close()}>Close details</button><p className="eyebrow">Component 0{selected+1}</p><h4 id="architecture-dialog-title">{item.name}</h4><p className="architecture-stack">{item.stack}</p><p>{item.description}</p><ul>{item.points.map(point=><li key={point}>{point}</li>)}</ul></dialog>
 <div className="architecture-notes"><article><h4>Live at the source</h4><p>Mobile saves into the same database Admin reads. Once a save succeeds, the record is available for authorized queries. What is visible in an already-open screen depends on that screen’s refresh behavior.</p></article><article><h4>External systems have their own timing</h4><p>Feed-monitoring readings and corporate synchronization follow their integration schedules. Those update intervals are separate from the availability of saved flock records in the shared database.</p></article></div>
 </div>;
}
