import type { AdminDataBundle } from "@/lib/types";

export const mockAdminData = {
  stats: {
    activePlacements: 12,
    farmsOnline: 4,
    barnsReady: 17,
    flocksInCycle: 9,
  },
  alerts: [
    {
      id: "alert-1",
      title: "Two barns need placement allocation for next week.",
      body: "South Creek Barn 4 and Mother Cluckers W3 both go open within the next six days.",
      tone: "warn",
    },
    {
      id: "alert-2",
      title: "Mortality variance above target at East Fork Barn B2.",
      body: "Daily submissions show a three-day spike that should be reviewed against ventilation and water notes.",
      tone: "danger",
    },
    {
      id: "alert-3",
      title: "Crew reporting coverage is healthy this morning.",
      body: "All active placements submitted the most recent daily packet before 9:00 AM.",
      tone: "good",
    },
  ],
  farmGroups: [
    {
      id: "group-1",
      groupName: "Smotherman Farms",
      legalName: "Smotherman Farms Ltd",
      integrator: "Pilgrim's",
      homeBase: "Bryan, TX",
      farmCount: 3,
      activePlacements: 7,
      primaryContact: "Ken Smotherman",
      status: "active",
    },
    {
      id: "group-2",
      groupName: "South Creek Growers",
      legalName: "South Creek Growers LLC",
      integrator: "Tyson",
      homeBase: "Franklin, TX",
      farmCount: 2,
      activePlacements: 4,
      primaryContact: "Maria Reyes",
      status: "active",
    },
  ],
  farms: [
    {
      id: "farm-1",
      farmGroupId: "group-1",
      farmGroupName: "Smotherman Farms",
      farmName: "Sedberry Farm",
      city: "Normangee",
      state: "TX",
      barnCount: 4,
      activePlacements: 3,
      managerName: "Ken H.",
      status: "active",
    },
    {
      id: "farm-2",
      farmGroupId: "group-1",
      farmGroupName: "Smotherman Farms",
      farmName: "Woape Farm",
      city: "Franklin",
      state: "TX",
      barnCount: 5,
      activePlacements: 4,
      managerName: "Maria R.",
      status: "active",
    },
    {
      id: "farm-3",
      farmGroupId: "group-1",
      farmGroupName: "Smotherman Farms",
      farmName: "Sulak Farm",
      city: "Hearne",
      state: "TX",
      barnCount: 3,
      activePlacements: 2,
      managerName: "Jon B.",
      status: "seasonal",
    },
    {
      id: "farm-4",
      farmGroupId: "group-2",
      farmGroupName: "South Creek Growers",
      farmName: "South Creek North",
      city: "Franklin",
      state: "TX",
      barnCount: 5,
      activePlacements: 3,
      managerName: "Maria R.",
      status: "active",
    },
  ],
  barnsByFarmId: {
    "farm-1": [
      { id: "barn-1", barnCode: "W1", capacity: 22800, currentPlacementCode: "123-W1", nextAvailableDate: "2026-05-14" },
      { id: "barn-2", barnCode: "W2", capacity: 22800, currentPlacementCode: "123-W2", nextAvailableDate: "2026-05-14" },
      { id: "barn-3", barnCode: "W3", capacity: 22800, currentPlacementCode: null, nextAvailableDate: "2026-04-06" },
      { id: "barn-4", barnCode: "E1", capacity: 21500, currentPlacementCode: "121-E1", nextAvailableDate: "2026-05-02" },
    ],
    "farm-2": [
      { id: "barn-5", barnCode: "B1", capacity: 24000, currentPlacementCode: "211-B1", nextAvailableDate: "2026-05-21" },
      { id: "barn-6", barnCode: "B2", capacity: 24000, currentPlacementCode: "211-B2", nextAvailableDate: "2026-05-21" },
      { id: "barn-7", barnCode: "B3", capacity: 24000, currentPlacementCode: "208-B3", nextAvailableDate: "2026-04-29" },
      { id: "barn-8", barnCode: "B4", capacity: 24000, currentPlacementCode: null, nextAvailableDate: "2026-04-07" },
      { id: "barn-9", barnCode: "B5", capacity: 24000, currentPlacementCode: null, nextAvailableDate: "2026-04-09" },
    ],
    "farm-3": [
      { id: "barn-10", barnCode: "A1", capacity: 20600, currentPlacementCode: "188-A1", nextAvailableDate: "2026-05-12" },
      { id: "barn-11", barnCode: "A2", capacity: 20600, currentPlacementCode: null, nextAvailableDate: "2026-04-04" },
      { id: "barn-12", barnCode: "A3", capacity: 20600, currentPlacementCode: "188-A3", nextAvailableDate: "2026-05-12" },
    ],
    "farm-4": [
      { id: "barn-13", barnCode: "N1", capacity: 24000, currentPlacementCode: "230-N1", nextAvailableDate: "2026-05-19" },
      { id: "barn-14", barnCode: "N2", capacity: 24000, currentPlacementCode: null, nextAvailableDate: "2026-04-10" },
      { id: "barn-15", barnCode: "N3", capacity: 24000, currentPlacementCode: "230-N3", nextAvailableDate: "2026-05-19" },
      { id: "barn-16", barnCode: "N4", capacity: 24000, currentPlacementCode: null, nextAvailableDate: "2026-04-12" },
      { id: "barn-17", barnCode: "N5", capacity: 24000, currentPlacementCode: "228-N5", nextAvailableDate: "2026-05-08" },
    ],
  },
  flocks: [
    {
      id: "flock-1",
      flockCode: "123",
      integrator: "Pilgrim's",
      placedDate: "2026-03-10",
      estimatedFirstCatch: "2026-04-17",
      femaleCount: 20400,
      maleCount: 2400,
      status: "active",
    },
    {
      id: "flock-2",
      flockCode: "121",
      integrator: "Pilgrim's",
      placedDate: "2026-02-28",
      estimatedFirstCatch: "2026-04-07",
      femaleCount: 19800,
      maleCount: 2200,
      status: "active",
    },
    {
      id: "flock-3",
      flockCode: "211",
      integrator: "Tyson",
      placedDate: "2026-03-18",
      estimatedFirstCatch: "2026-04-25",
      femaleCount: 21400,
      maleCount: 2600,
      status: "active",
    },
    {
      id: "flock-4",
      flockCode: "230",
      integrator: "Tyson",
      placedDate: "2026-04-08",
      estimatedFirstCatch: "2026-05-16",
      femaleCount: 22000,
      maleCount: 2400,
      status: "scheduled",
    },
  ],
  placementHints: [
    {
      placementCode: "230-W3",
      farmName: "Sedberry Farm",
      barnCode: "W3",
      startDate: "2026-04-08",
      projectedEndDate: "2026-05-19",
      flockCode: "230",
    },
    {
      placementCode: "230-B4",
      farmName: "Woape Farm",
      barnCode: "B4",
      startDate: "2026-04-08",
      projectedEndDate: "2026-05-19",
      flockCode: "230",
    },
  ],
  activePlacements: [
    {
      id: "active-1",
      placementCode: "123-W1",
      placementId: "placement-123-w1",
      farmGroupId: "group-1",
      farmGroupName: "Smotherman Farms",
      farmId: "farm-1",
      farmName: "Sedberry Farm",
      barnId: "barn-1",
      barnCode: "W1",
      flockCode: "123",
      integrator: "Pilgrim's",
      placedDate: "2026-03-10",
      estimatedFirstCatch: "2026-04-17",
      ageDays: 22,
      headCount: 22800,
      completionPercent: 100,
      submissionStatus: "submitted",
    },
    {
      id: "active-2",
      placementCode: "123-W2",
      placementId: "placement-123-w2",
      farmGroupId: "group-1",
      farmGroupName: "Smotherman Farms",
      farmId: "farm-1",
      farmName: "Sedberry Farm",
      barnId: "barn-2",
      barnCode: "W2",
      flockCode: "123",
      integrator: "Pilgrim's",
      placedDate: "2026-03-10",
      estimatedFirstCatch: "2026-04-17",
      ageDays: 22,
      headCount: 22800,
      completionPercent: 88,
      submissionStatus: "pending",
    },
    {
      id: "active-3",
      placementCode: "121-E1",
      placementId: "placement-121-e1",
      farmGroupId: "group-1",
      farmGroupName: "Smotherman Farms",
      farmId: "farm-1",
      farmName: "Sedberry Farm",
      barnId: "barn-4",
      barnCode: "E1",
      flockCode: "121",
      integrator: "Pilgrim's",
      placedDate: "2026-02-28",
      estimatedFirstCatch: "2026-04-07",
      ageDays: 33,
      headCount: 22000,
      completionPercent: 100,
      submissionStatus: "submitted",
    },
    {
      id: "active-4",
      placementCode: "211-B1",
      placementId: "placement-211-b1",
      farmGroupId: "group-1",
      farmGroupName: "Smotherman Farms",
      farmId: "farm-2",
      farmName: "Woape Farm",
      barnId: "barn-5",
      barnCode: "B1",
      flockCode: "211",
      integrator: "Tyson",
      placedDate: "2026-03-18",
      estimatedFirstCatch: "2026-04-25",
      ageDays: 14,
      headCount: 24000,
      completionPercent: 100,
      submissionStatus: "submitted",
    },
    {
      id: "active-5",
      placementCode: "211-B2",
      placementId: "placement-211-b2",
      farmGroupId: "group-1",
      farmGroupName: "Smotherman Farms",
      farmId: "farm-2",
      farmName: "Woape Farm",
      barnId: "barn-6",
      barnCode: "B2",
      flockCode: "211",
      integrator: "Tyson",
      placedDate: "2026-03-18",
      estimatedFirstCatch: "2026-04-25",
      ageDays: 14,
      headCount: 24000,
      completionPercent: 62,
      submissionStatus: "attention",
    },
    {
      id: "active-6",
      placementCode: "208-B3",
      placementId: "placement-208-b3",
      farmGroupId: "group-1",
      farmGroupName: "Smotherman Farms",
      farmId: "farm-2",
      farmName: "Woape Farm",
      barnId: "barn-7",
      barnCode: "B3",
      flockCode: "208",
      integrator: "Tyson",
      placedDate: "2026-03-01",
      estimatedFirstCatch: "2026-04-08",
      ageDays: 31,
      headCount: 24000,
      completionPercent: 100,
      submissionStatus: "submitted",
    },
    {
      id: "active-7",
      placementCode: "188-A1",
      placementId: "placement-188-a1",
      farmGroupId: "group-1",
      farmGroupName: "Smotherman Farms",
      farmId: "farm-3",
      farmName: "Sulak Farm",
      barnId: "barn-10",
      barnCode: "A1",
      flockCode: "188",
      integrator: "Pilgrim's",
      placedDate: "2026-03-05",
      estimatedFirstCatch: "2026-04-12",
      ageDays: 27,
      headCount: 20600,
      completionPercent: 100,
      submissionStatus: "submitted",
    },
    {
      id: "active-8",
      placementCode: "188-A3",
      placementId: "placement-188-a3",
      farmGroupId: "group-1",
      farmGroupName: "Smotherman Farms",
      farmId: "farm-3",
      farmName: "Sulak Farm",
      barnId: "barn-12",
      barnCode: "A3",
      flockCode: "188",
      integrator: "Pilgrim's",
      placedDate: "2026-03-05",
      estimatedFirstCatch: "2026-04-12",
      ageDays: 27,
      headCount: 20600,
      completionPercent: 94,
      submissionStatus: "pending",
    },
    {
      id: "active-9",
      placementCode: "230-N1",
      placementId: "placement-230-n1",
      farmGroupId: "group-2",
      farmGroupName: "South Creek Growers",
      farmId: "farm-4",
      farmName: "South Creek North",
      barnId: "barn-13",
      barnCode: "N1",
      flockCode: "230",
      integrator: "Tyson",
      placedDate: "2026-04-08",
      estimatedFirstCatch: "2026-05-16",
      ageDays: 7,
      headCount: 24000,
      completionPercent: 100,
      submissionStatus: "submitted",
    },
    {
      id: "active-10",
      placementCode: "230-N3",
      placementId: "placement-230-n3",
      farmGroupId: "group-2",
      farmGroupName: "South Creek Growers",
      farmId: "farm-4",
      farmName: "South Creek North",
      barnId: "barn-15",
      barnCode: "N3",
      flockCode: "230",
      integrator: "Tyson",
      placedDate: "2026-04-08",
      estimatedFirstCatch: "2026-05-16",
      ageDays: 7,
      headCount: 24000,
      completionPercent: 81,
      submissionStatus: "pending",
    },
    {
      id: "active-11",
      placementCode: "228-N5",
      placementId: "placement-228-n5",
      farmGroupId: "group-2",
      farmGroupName: "South Creek Growers",
      farmId: "farm-4",
      farmName: "South Creek North",
      barnId: "barn-17",
      barnCode: "N5",
      flockCode: "228",
      integrator: "Tyson",
      placedDate: "2026-03-28",
      estimatedFirstCatch: "2026-05-05",
      ageDays: 18,
      headCount: 24000,
      completionPercent: 100,
      submissionStatus: "submitted",
    },
  ],
} as unknown as AdminDataBundle;
